spring:
    jpa:
        hibernate:
            ddl-auto: update
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://10.1.1.174:3306/uaps_high_way?useUnicode=true&characterEncoding=utf8&autoReconnect=true
        username: root
        password: 123456
#log配置
logging:
  file: weChatApiServer.log
  level.com.favorite: DEBUG
  level.org.springframework.web: INFO
  level.org.hibernate: ERROR
